### ISSUE TITLE
Structures and mobs not spawning 2.1.0-1.16.3

### ISSUE THREAD

**Issue by redeyedkaneki** [Alex-the-666/Ice_and_Fire#3107] opened 2020-11-06 01:37 UTC
ive tried different versions of forge, ice and fire, and citadel. ive spent several hours tinkering and looking around my worlds in creative looks for any mobs that should be spawning and theres just nothing. i have the main menu background and jei ice and fire update but nothing else id appreciate any help

**Comment by azuichh** [comment] 2020-11-06 01:47
did you try to use the 2.1.1 ?

**Comment by redeyedkaneki** [comment] 2020-11-06 02:04
i tried before gonna try it again, the mobs spawn around 1000 blocks away right?

**Comment by redeyedkaneki** [comment] 2020-11-06 02:08
im still not seeing anything at all

**Comment by azuichh** [comment] 2020-11-06 02:08
i was asking bc you said 2.1.0 and yes the mobs spawn around 1000 bock but you can edit that in the mod config

**Comment by redeyedkaneki** [comment] 2020-11-06 02:10
so the only thing thats around now are cemeteries and the ghosts but with ice and fire should come dragons and a bunch of other mobs right?

**Comment by azuichh** [comment] 2020-11-06 02:17
i will try if i found somthing

**Comment by redeyedkaneki** [comment] 2020-11-06 02:25
cool i appreciate it a ton

**Comment by azuichh** [comment] 2020-11-06 03:04
for what i see nothing work i try to remove the config that make the mobs spawn 2k block away but nothing so we can just wait for the 2.1.2 to patch that

**Comment by redeyedkaneki** [comment] 2020-11-06 03:07
well the mobs also just dont spawn in at all regardless of the distance. i tried going several thousand blocks away and still not other mobs just ghosts

**Comment by redeyedkaneki** [comment] 2020-11-06 03:07
im gonna try sorting through my other mods maybe one of them is keeping ice and fire from working

**Comment by azuichh** [comment] 2020-11-06 03:09
i don't think it's a mod conflict i try with only i/f

**Comment by redeyedkaneki** [comment] 2020-11-06 03:12
were the mobs spawning for you?

**Comment by redeyedkaneki** [comment] 2020-11-06 03:12
like at all?

**Comment by azuichh** [comment] 2020-11-06 03:13
i didn't find any mob like i found nothing

**Comment by azuichh** [comment] 2020-11-06 03:16
in the mod config there is a config called "Dangerous World Gen Dist From Spawn" i set this config to 1 and after creating a new wolrd i walk 4k block in spectator and nothing

**Comment by redeyedkaneki** [comment] 2020-11-06 03:19
is this happening only on 2.1.1?

**Comment by azuichh** [comment] 2020-11-06 03:25
idk all the test i do for this bug was in  2.1.1

**Comment by Neko2n** [comment] 2020-11-06 08:58
I have found something using Blame (better latest.log reports), all values for generating anything seem to be turned to false by default. I have tested this both with everything in my config file set to true and with everything in my config file set to false, it's not inverting the config settings it's just straight-up ignoring them.

My assumption is that this issue is caused by the mod being unable to hook into the config file and therefore reverting to default values (which are apparently false for everything).

**Comment by redeyedkaneki** [comment] 2020-11-06 20:27
could that be because of other mods that add other mobs? maybe there just isnt enough space for all the mobs to spawn so all ice and fire mobs are just set not to spawn?

**Comment by redeyedkaneki** [comment] 2020-11-06 20:51
just tried removing all the nonessential mods with no luck still nothing spawning... everything is in the creative mode inventory like i can put dragon eggs down and equip the weapons but nothing is spawning its so annoying

**Comment by redeyedkaneki** [comment] 2020-11-06 21:48
> I have found something using Blame (better latest.log reports), all values for generating anything seem to be turned to false by default. I have tested this both with everything in my config file set to true and with everything in my config file set to false, it's not inverting the config settings it's just straight-up ignoring them.
> 
> My assumption is that this issue is caused by the mod being unable to hook into the config file and therefore reverting to default values (which are apparently false for everything).

so basically the mod version im using is broken and if i want to play the mod ill have drop to any older version?

**Comment by Neko2n** [comment] 2020-11-07 09:21
> > I have found something using Blame (better latest.log reports), all values for generating anything seem to be turned to false by default. I have tested this both with everything in my config file set to true and with everything in my config file set to false, it's not inverting the config settings it's just straight-up ignoring them.
> > My assumption is that this issue is caused by the mod being unable to hook into the config file and therefore reverting to default values (which are apparently false for everything).
> 
> so basically the mod version im using is broken and if i want to play the mod ill have drop to any older version?

Yeah, newest 1.16.3 jar is broken. This is a very well-known bug, and I'm really hoping it gets fixed soon.

**Comment by AlexModGuy** [comment] 2020-11-19 21:33
fixed in 2.1.2

**Closed as completed by AlexModGuy** 2020-11-19 21:33 UTC
