### ISSUE TITLE
Achievement Bug

### ISSUE THREAD

**Issue by pezrabioso** [Alex-the-666/Ice_and_Fire#235] opened 2017-05-19 00:35 UTC
For some reason, I got the [Hiccup] achievement from killing a baby dragon when it says you should get it when you get killed by a dragon ( I had gotten killed by a dragon before and hadn't gotten the achievement).

**Comment by Alex-the-666** [comment] 2017-05-19 02:22
duplicate of #184

**Closed by Alex-the-666** 2017-05-19 02:22 UTC
