### ISSUE TITLE
2.1.9 Ice Dragon Still Crashing Server (Ice and Fire Mod)

### ISSUE THREAD

**Issue by Twinjoker** [Alex-the-666/Ice_and_Fire#4471] opened 2022-05-05 18:17 UTC
A friend and I found an adult dragon and once it attacked us it crashed the server. We have since logged in and tried to escape from it but it crashes the server every time we are near it which makes progressing with dragons impossible. Is there a current fix to this? Please help as soon as you can, thank you.

**Comment by DigitalWendigo** [comment] 2022-05-05 18:20
It's hard to help anyone if no mod list and log file is provided.

**Comment by Twinjoker** [comment] 2022-05-05 19:28
ATM6 for Mod List and log file below

[crash-2022-05-05_17.25.55-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8635443/crash-2022-05-05_17.25.55-server.txt)

**Comment by DigitalWendigo** [comment] 2022-05-05 19:49
Please report this issue to the ATM6 modpack developer.
The modpack developer has also suggested to several people reporting crashes, to join their discord server and reporting the issues there directly. 

"[DAmNRelentless](https://github.com/DAmNRelentless) commented [on Jun 16, 2021](https://github.com/AllTheMods/ATM-6/issues/1804#issuecomment-861833641)
If you need help with crash-report, I'd suggest you join the Discord and ask in the respective help channels because in 90% of these cases, the crash-report aren't related to a bug in the pack.

Your crash is a tick-time shutdown. The server watchdog detected that the server can't keep up or froze somewhere so it was shut down.
Please ask in the Discord for assistance if you need help resolving this issue."

**Comment by DigitalWendigo** [comment] 2022-05-10 17:16
This issue can probably be closed as it seems like it's not caused by ice and fire in a vanilla environment. 
In the case that it's something else, I think a new issue should be opened.

**Closed as completed** 2023-02-28 22:29 UTC
