### ISSUE TITLE
Bestiary not showing text

### ISSUE THREAD

**Issue by f-sage** [Alex-the-666/Ice_and_Fire#1668] opened 2019-08-09 10:40 UTC
So I got myself the (1.8.0) latest build from this repository and there is no text on pages except the entry title. I only see the illustrations on their proper place. 
I tried to change modpack to one with vanilla font (no russificator), switching game locale to en/esp/whatever, 'forced unicode font' option, changing 'using vanilla font' cfg to true. None of these worked.

What do I do wrong ppl...

**Comment by zucaluca** [comment] 2019-08-09 10:51
Assuming you tried adding manuscripts to the bestiary using the lectern already?

**Comment by f-sage** [comment] 2019-08-09 14:09
Well I tested it on full book in creative so yes
And recipes coded in txt file are not there either

**Comment by Xorbah** [comment] 2019-08-09 15:05
Could you drop the build here?

**Comment by f-sage** [comment] 2019-08-09 15:12
you could just clone the repository and run gradle bat file but fine
[iceandfire-1.8.0.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/3486914/iceandfire-1.8.0.zip)

**Comment by MasterOfTheCats** [comment] 2019-08-09 15:47
You do know 1.8 isn’t even out yet, right?

**Comment by f-sage** [comment] 2019-08-09 15:49
Yeah I know. This debug version is just labeled 1.8.0.
But I probably should edit the report, thanks.

**Comment by Sholooloo** [comment] 2019-08-09 15:56
Dude, close this, you're not supposed to even have 1.8 yet, that's your issue

**Comment by AlexModGuy** [comment] 2019-08-09 16:10
@ f-sage The issue is that the current russian translations were not in UTF-8, so they were not loaded, this is normal behavior and means that someone who knows russian will have to retranslate all of it in UTF-8 format.

**Comment by f-sage** [comment] 2019-08-09 16:13
What. It's not about russian... None of the languages work.

**Comment by AlexModGuy** [comment] 2019-08-09 16:31
hmm youre correct, the console is spamming

java.io.FileNotFoundException: iceandfire:lang/bestiary/en_us/introduction_0.txt

**Closed as completed** 2019-08-09 16:34 UTC
