### ISSUE TITLE
Mowzies mobs and Ice and Fire problems

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#735] opened 2018-06-09 04:35 UTC
When petrified, mobs can still attack or move to attack
Spear one-shotting dragons since they're considered an animal
Ice dragons can be frozen by the ice crystal

**Comment by AlexModGuy** [comment] 2018-06-15 02:58
dupe of #307 make sure you check if other issues similar to yours exist before you post them

**Closed as completed by AlexModGuy** 2018-06-15 02:58 UTC
