### ISSUE TITLE
Petrified chickens still walk around 1.5.0

### ISSUE THREAD

**Issue by Frosty8-0** [Alex-the-666/Ice_and_Fire#830] opened 2018-06-19 04:29 UTC
Sometimes petrified chickens (by gorgon) still walk around.

**Comment by BlueWither** [comment] 2018-06-19 09:20
No Mowzie's Mobs?

**Comment by Frosty8-0** [comment] 2018-06-19 09:59
Yes I was using Mowzies Mobs..  Are they incompatible?

**Comment by BlueWither** [comment] 2018-06-19 10:04
I do not know the cause, but when using Mowzie's Mobs the stone statue seems to move.
That problem has already been reported.

**Comment by AlexModGuy** [comment] 2018-06-19 18:14
dupe of mowzies mob issue

**Closed as completed by AlexModGuy** 2018-06-19 18:14 UTC
