### ISSUE TITLE
Dragon textures glitching out/ missing [video]

### ISSUE THREAD

**Issue by Zeraphynx** [Alex-the-666/Ice_and_Fire#227] opened 2017-04-28 18:17 UTC
https://gfycat.com/AfraidColorfulGorilla
https://gfycat.com/SpiritedFrankAsianlion
Used in conjunction with the latest [All the mods] modpack with an extra Tail and Mo'bend mods on the Curse/Twitch launcher

**Comment by Alex-the-666** [comment] 2017-04-28 22:48
Duplicate of #151. Please see if there are any other issues similar to yours before opening a new one.

Also this is caused due to some mod changing the default item renderer. IIRC it is AE2.

**Closed by Alex-the-666** 2017-04-28 22:48 UTC
