### ISSUE TITLE
Critical error detected whilst generating Structure iceandfire:graveyard（1.16.5-2.1.7）

### ISSUE THREAD

**Issue by kabosu-kabokabo-61** [Alex-the-666/Ice_and_Fire#3950] opened 2021-06-12 07:22 UTC
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
The game suddenly crashes when I move to a certain point.

**To Reproduce**
1.Go to the certain point. In my case, it was near the mesa.
2. See error.

**Additional context**
I've talked to the author of terraforged, and apparently there's a problem with the structure of this mod.

[crash-2021-06-12_14.59.38-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6641817/crash-2021-06-12_14.59.38-client.txt)

**Comment by Irellafael** [comment] 2021-06-12 12:46
This happened to me too.



[crash-2021-06-11_22.54.44-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6642185/crash-2021-06-11_22.54.44-server.txt)

**Comment by Doominic08** [comment] 2021-06-12 20:13
This happens to me whenever i load in a new graveyard or mausoleum, i just changed the config file so that new mausoleums and graveyards don't generate. if they don't generate in the first place: the game wont crash. really hope there is a fix tho

**Comment by Ravarath** [comment] 2021-06-13 02:54
Happened to me as well, while I was riding a boat in an ocean biome, loading a lot of chunks at once. I believe it's crashing on loading the chunk with the graveyard.

[crash-2021-06-12_19.47.49-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6643191/crash-2021-06-12_19.47.49-server.txt)

**Comment by TheBv** [comment] 2021-06-14 16:04
Would it be possible to provide the world the crash appears in? I've been trying to recreate this but haven't had any luck so far :/
But maybe @TelepathicGrunt has any ideas?

**Comment by TelepathicGrunt** [comment] 2021-06-14 16:22
Can you all please put on the mod called [Blame](https://www.curseforge.com/minecraft/mc-mods/blame) and reproduce the crash. The go into the logs folder above the mods folder, grab the latest.log file, and drag the file to here to upload for us to see. Without the full log and Blame, there's no really way to troubleshot exactly what the issue could be. 

The funny thing is crashlogs are annoying as they never show enough info lol. Especially if another mod wreck processors files in a way that cascades and breaks many worldgen mods but that kind of info won't show up in the crashlog. Only latest.log file and with Blame on.

**Comment by Ravarath** [comment] 2021-06-14 16:54
Here you go, sir! Hope this helps.

[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6649976/latest.log)

**Comment by TelepathicGrunt** [comment] 2021-06-14 17:58
I see the mod Planet has a few broken json files but it doesn't seem like that error cascaded. The NBT file for the structure was found as Blame never made a missing NBT file report. The code in `net.minecraft.world.gen.feature.structure.TemplateStructurePiece.func_230383_a_(SourceFile:62)` shouldn't even be able to be crashed. I am assuming it is this that is crashing but I don't see how as there's a null check. Even if .getString("metadata") returned null, the stacktrace would show the crash in handleDataMarker but it doesn't. It says it crashes in TemplateStructurePiece. 
```java
 for(Template.BlockInfo template$blockinfo : this.template.filterBlocks(this.templatePosition, this.placeSettings, Blocks.STRUCTURE_BLOCK)) {
  if (template$blockinfo.nbt != null) {
     StructureMode structuremode = StructureMode.valueOf(template$blockinfo.nbt.getString("mode"));
     if (structuremode == StructureMode.DATA) {
        this.handleDataMarker(template$blockinfo.nbt.getString("metadata"), template$blockinfo.pos, p_230383_1_, p_230383_4_, p_230383_5_);
     }
   }
 }
```

it is very odd... Especially since this one person got it to occur with practically just ice and fire. 
![image](https://user-images.githubusercontent.com/40846040/121936343-85f06c00-cd17-11eb-92c3-bb8acad29ea1.png)

**Comment by Irellafael** [comment] 2021-06-14 18:12
I figured out it is something in my save game. So when I create a new world, it generates said structures without a problem (for as far as I've played now). 

So my save game is from the previous version, I can load it, but as soon as I move out of my spawn area and one of the structures gets close and tries to generate, the game crashes.

Not sure if it helps anything, but that's what I found out so far. I can try to reproduce the crash in a bit.

**Comment by TheBv** [comment] 2021-06-14 19:11
Okay so the since the mappings changed the code for the template structure changed as well. This is now the relevant code:
```Java
this.placeSettings.setBoundingBox(p_230383_5_);
this.boundingBox = this.template.getMutableBoundingBox(this.placeSettings, this.templatePosition);
```
placeSettings in this case is null when using a world with structures that have previously been generated.
This seems to have something to do with the dummy piece that was introduced the reduce logspam which doesn't seem to have any placeSettings. I'll try create a fix for this in a bit :)

**Comment by Irellafael** [comment] 2021-06-14 19:12
For some weird reason I cannot get my save game to crash anymore while having Blame installed. I guess I'll just keep playing until it does.

**Comment by TelepathicGrunt** [comment] 2021-06-14 21:07
Interesting. I guess I should go and update Blame to detect this edge case in case any other mod does the same thing. Thank you for the insight!

**Comment by TelepathicGrunt** [comment] 2021-06-14 21:08
Interesting. I guess I should go and update Blame to detect this edge case in case any other mod does the same thing. Thank you for the insight!

**Closed as completed** 2021-06-16 17:56 UTC
