### ISSUE TITLE
Mymex AI seem to cause crash (2.1.7 - 2.1.8)

### ISSUE THREAD

**Issue by User-green** [Alex-the-666/Ice_and_Fire#4026] opened 2021-06-25 04:12 UTC
**Describe the bug**
Bad arguments for random() in mymex AI in v.2.1.7 seem (according to the logs) to cause sever hard crash.
**To Reproduce**
0. Install OpenJRE `adoptopenjdk-8-openj9-jre/buster 8u292-b10.openj9-0.26.0-3 amd64`. May be critical, but as well may be not.
1. Create any world with this mod on nogui server. 
2. Locate any mymex hive
3. Wonder around for a while.
4. Got your server creshed
5. Open logs
6. ~~PROFIT!~~ See the bug.

**Expected behavior**
Obviusly - absents of any crashes.
**Screenshots**
N/A
**Additional context**

- I havent see the cause with my own eyes, only read logs and listen to players.
- This version of the OJRE have caused problems with other mods. This may be its fault.
- There is a log - [crash-2021-06-25_04.45.23-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6713458/crash-2021-06-25_04.45.23-server.txt)

P.S. Also at v.2.1.8 I have TPS problems. Thay are so bad, that server got terminated by wachdog, but I am not shure if it caused by this mod solo or by mod conflict. Later I will do reserches and open new issue. 

UPD.
Edited to mach the form.

**Comment by rafannunzi** [comment] 2021-06-26 20:31
I just discovered this same issue a few days ago. My fix to make the game playable until the issue is resolved was to disable the Myrmex from spawning and use the /kill command to remove any existing mobs. It was the weirdest thing; the server would run fine, but as soon as we'd walk into this desert, massive TPS issues would persist until the server crashed or we left. Removing the Myrmex immediately fixed it.

**Comment by User-green** [comment] 2021-06-27 13:01
> I just discovered this same issue a few days ago. My fix to make the game playable until the issue is resolved was to disable the Myrmex from spawning and use the /kill command to remove any existing mobs. It was the weirdest thing; the server would run fine, but as soon as we'd walk into this desert, massive TPS issues would persist until the server crashed or we left. Removing the Myrmex immediately fixed it.

You right. I updated mod to 2.1.8 while not enableing mymex spawn and issue with wachdog termination never pop up again.

**Comment by TheBv** [comment] 2021-06-29 15:46
Lowering the value for the maximum wander radius for myrmex should also fix this issue to some extend it won't be perfect but try a value <=25

**Comment by User-green** [comment] 2021-07-01 19:49
> 
> 
> Lowering the value for the maximum wander radius for myrmex should also fix this issue to some extend it won't be perfect but try a value <=25

Thank you, but for me it is easyer to just disable the spawn of them.

**Comment by AlexModGuy** [comment] 2021-08-27 19:31
fixed in 2.1.9

**Closed as completed by AlexModGuy** 2021-08-27 19:31 UTC
