### ISSUE TITLE
Cant ride ice dragon underwater as it would kick you out [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3624] opened 2021-02-27 11:30 UTC
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
My ice dragon got into deep water and sink down, I can mount it to ride it out.

**To Reproduce**
1. Mount tamed ice dragon
2. Go into deep water and let it sink
3. It will kick you out, even id you try to mount it again, it wont let you.

**Expected behavior**
The player should still be able to hold onto the summerged ice dragon and control it.

**Screenshots**

**Additional context**

**Comment by TheBv** [comment] 2021-02-27 14:34
I can't reproduce this with the newest IaF/forge version. This should have been something that was fixed with 2.1.6 alongside hippocampi being rideable underwater again. Can you confirm that you're using IaF version 2.1.6?

**Comment by kihgy** [comment] 2021-02-27 16:35
Yes I remember at was indeed 2.1.6 when I decided to post this, but another question is, did I really mounted the dragon?

**Closed as completed** 2021-02-28 11:50 UTC
