### ISSUE TITLE
Dragons don’t perform any big roar or grabbing animation [2.1.7]

### ISSUE THREAD

**Issue by TracedK** [Alex-the-666/Ice_and_Fire#3977] opened 2021-06-16 18:50 UTC
**Describe the bug**
- Dragons don’t perform any animation when going for a big roar and grabbing attack. For a big roar they just hover in the air and come back down. For the grab attack they don’t open their mouths or shake.
**To Reproduce**
See a dragon animation. I’m using a tamed dragon.

**Comment by BugmanBugman** [comment] 2021-06-16 19:17
This will be fixed by TheBv’s latest patch. Duplicate of #3973

**Closed as completed** 2022-04-26 17:35 UTC
