### ISSUE TITLE
Hippogryphs constantly spawning in the badlands plateau biome.

### ISSUE THREAD

**Issue by Romoslayer** [Alex-the-666/Ice_and_Fire#4368] opened 2022-01-12 22:57 UTC
Not sure why but it looks like hippogryphs were constantly spawning when I was in the badlands plateau biome...
Video of the bug: https://www.youtube.com/watch?v=tIE6OgpMY54
Mod Version: 1.16.5-2.1.9
MC Version: forge-1.16.5-36.2.20
Link to logs file: https://drive.google.com/file/d/1f_mJ0xh9H2iwBR_yySjLbOZzbtpZp_Hw/view?usp=sharing
Modpack the bug occurred on: https://www.curseforge.com/minecraft/modpacks/nswtcty
^ (incase you need to attempt reproducing the bug yourself, just go to a badlands plateau biome).

**Comment by EverettSummer** [comment] 2022-01-13 11:00
The spawn biome can be configured. Did you try modify the config in config/ice-and-fire/hippogryphs.

**Comment by Romoslayer** [comment] 2022-01-13 18:22
This is my current iceandfire client file
https://drive.google.com/file/d/1zXCWfCKUHXVewKtAl2lvtn9zSPpyxmd1/view?usp=sharing

**Comment by EverettSummer** [comment] 2022-01-15 08:02
It's not in the `iceandfire-client.toml` . instead. You should go to the server (or if you are playing SP, you can go to your client ) config folder. and there is a folder called `iceandfire`. it has config files for every type of mob in this mod. There are 8 types of hippogryph config files each subspecies will have its own biome setting

**Comment by Romoslayer** [comment] 2022-02-17 02:02
I have not changed any of the config files in that folder.
https://drive.google.com/drive/folders/1yQBd3CmUdEakvtalkItfd5lgvyYkKHPX?usp=sharing
Biome configs ^

**Comment by DigitalWendigo** [comment] 2022-04-27 10:24
Out of curiousity, are you using optifine with Entity Culling? 
That combination can also make some mobs invisible at a random point. 
So for anyone using your pack, I'd suggest adding that to the notice board at the front page.

**Comment by Romoslayer** [comment] 2022-04-27 16:27
I am using Entity Culling but not Optifine.

**Comment by DigitalWendigo** [comment] 2022-04-27 16:42
Any other mods that influence mob spawning conditions in any way?
Perhaps either of the dependancy libraries you have in the modpack?
There are a lot of mods in the pack, by the looks of it. 
Citadel for example increases the amount of mobs spawned on chunk generation. 
If another mod does something even remotely similar, then they might conflict with each other and break how certain mobs spawn.

**Comment by DigitalWendigo** [comment] 2022-04-27 16:51
Oh on that note, I may have an idea. 
You have a mod in that pack called 'respawnable animals'
Now I could be wrong, but if Hyppogryphs are counted as animals, then that mod might be affecting their spawning. 
Resulting in an endless respawning. If the mod has a blacklist in its config file, maybe add hyppogryps to it and see if that fixes the issue?

**Comment by Romoslayer** [comment] 2022-04-27 17:34
I dont think it is respawnable animals as this issue first began before I had it in this pack, that mod also has a mob cap whereas when this issue occurs ice and fire mobs endlessly spawn.

**Comment by DigitalWendigo** [comment] 2022-04-27 17:37
That's odd. 
I'm personally interested in this issue because some of the mods you have in your pack, I have in my private pack as well. 
Yet I don't have the issue with endlessly spawning hyppogryps in the badlands biomes. 
Have you tried with just ice and fire and citadel installed?

**Comment by Romoslayer** [comment] 2022-04-27 17:40
I have not but, I dont think it would occur if I only used those two mods as the endless spawning seems to happen randomly and not all the time (I don't know how to reproduce it either, seems to just happen as I fly around single player worlds).

**Comment by DigitalWendigo** [comment] 2022-04-27 17:49
It's going to be tedious, but I suggest disabling any mods that change spawning in anyway, one mod at a time. 
The only reasonable explanation to this is that one of the many mods you have, is messing with the upper spawn limit of hyppogryphs. 
If the issue doesn't happen with just ice and fire installed and nothing else, then it's another mod conflict. 
Furthermore, I may suggest posting the log file on a different site, as google drive has already removed your log file by the looks of it, making it impossible for others to take a peek.

**Comment by Romoslayer** [comment] 2022-04-27 17:59
I will attempt to see if I can reproduce the bug and get a log file.

**Comment by DigitalWendigo** [comment] 2022-05-10 18:38
Have you been able to reproduce this and get a log file? 
Also I suggest reproducing this with the latest Alpha release found here: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/2.1.10-alpha2

**Comment by Romoslayer** [comment] 2022-05-10 19:08
No, I haven't been able to reproduce it. I created a couple worlds that spawned me in a biome that this kind of thing would usually happen in (usually jungle biomes) and there were a couple amphithere's that spawned on world gen but no new ones spawned.

**Comment by DigitalWendigo** [comment] 2022-05-10 19:30
Then perhaps until this issue appears again, it might be best to close it and quote that another mod causes this.

**Closed as completed** 2022-05-11 16:33 UTC
