### ISSUE TITLE
ice and fire dragon eggs despawn 2.1.6-1.16.4

### ISSUE THREAD

**Issue by starfall18** [Alex-the-666/Ice_and_Fire#3895] opened 2021-05-22 18:35 UTC
When placing ice dragon in water and fire dragon in fire, they start hatching but after a while they despawn without the dragons anywhere. They despawn way before they should even hatch... this issue does not seem to affect the lightning dragon eggs though.
There have been several complaints on the server im on that the eggs have gone missing. It is confirmed that it is not a visual glitch that has happened in the past. The eggs just disappear.

**Comment by TheBv** [comment] 2022-05-14 20:30
Duplicate of #3809

**Closed as completed by TheBv** 2022-05-14 20:30 UTC
Labels: DragonEgg
