### ISSUE TITLE
Conflict with Pollution of the Realms and Feature Request

### ISSUE THREAD

**Issue by Keyedrin** [Alex-the-666/Ice_and_Fire#1882] opened 2019-09-29 20:01 UTC
Deathworms cause a crash occasionally when Pollution of the Realms is installed. I will post more info and a crash log when I get the chance.

I would appreciate a config option to deregister entity types if that is possible, as disabling deathworms from spawning helps but doesn't affect currently spawned deathworms, and running a kill command block doesn't affect them before the server crashes.

**Comment by AlexModGuy** [comment] 2019-09-29 21:19
crash log please

**Comment by Keyedrin** [comment] 2019-09-30 01:32
https://pastebin.com/eewqC1WY
There's no actual crash log relating to it in crash-reports, so I grabbed the relevant information out of the server logs. The formatting might be a bit wonky, had to grab it from a log off my server host and try to make it a bit more legible. It repeats for several thousand lines so I just grabbed about 100.

**Comment by AlexModGuy** [comment] 2019-09-30 01:45
fixed on our end but this was caused by another mod:

>at com.endertech.minecraft.mods.adpother.sources.SourceLiving.getOutletPosition(SourceLiving.java:33) ~[SourceLiving.class:?]
at com.endertech.minecraft.mods.adpother.sources.SourceLiving.emitFrom(SourceLiving.java:25) ~[SourceLiving.class:?]      

I suggest bringing this up to the devs of a "endertech" mod.

**Closed as completed** 2019-09-30 01:44 UTC
Labels: Other Creature, Other Mod Causes This
