### ISSUE TITLE
[Bug]: Armors Shrunk in Alpha 7

### ISSUE THREAD

**Issue by SuperStefan97** [Alex-the-666/Ice_and_Fire#5024] opened 2023-11-15 14:31 UTC
### What happened?

The alpha 7 seems to be working pretty good. So far, I can confirm not only but other players are experimenting this:
![image-6](https://github.com/AlexModGuy/Ice_and_Fire/assets/96614259/058583e5-fc5d-4aeb-9d5d-99f906916250)
Armors render small in the players... looking pretty uncomfortable lol.
Thanks for your great work on the mod, really appreciated by all the comunity.

### Minecraft Version

1.20.1

### Ice and Fire version

Alpha 7

### Citadel version

Latest

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment] 2024-01-03 12:30
Duplicate of https://github.com/AlexModGuy/Ice_and_Fire/issues/4936

**Closed as not planned by TheBv** 2024-01-03 12:30 UTC
Labels: bug
