### ISSUE TITLE
No damage on Ghost Sword

### ISSUE THREAD

**Issue by Quatronomikon** [Alex-the-666/Ice_and_Fire#4084] opened 2021-07-19 14:11 UTC
**Describe the bug**
I used the sword by trowing it with rightclick, and it got not damage by hitting

**To Reproduce**
1. Get a ghost sword
2. Use it by rightklicking in survival mode and hit a mob
3. Blade don't get damage

**Expected behavior**
The sword get damaged

**Screenshots**
![2021-07-19_16 07 02](https://user-images.githubusercontent.com/70969627/126173674-0ede088b-292a-4b75-a071-40ac6313495e.png)

**Comment by TheBv** [comment] 2022-05-09 00:20
Duplicate of #3810

**Closed as completed by TheBv** 2022-05-09 00:20 UTC
