### ISSUE TITLE
Pixie Crash ConcurrentModificationException

### ISSUE THREAD

**Issue by R0gu3P403n1x** [Alex-the-666/Ice_and_Fire#661] opened 2018-04-30 00:54 UTC
I am not certain if it was the hovel, or the pixie that caused the crash, but when a player had both on screen it crashed the whole server. Just minecraft, not a BSOD or crashing windows, just for clarification.

Minecraft version is 1.12.2
Forge version is 14.23.3.2675
ice and fire version is 1.4.0

I do have other mods, so it could be a conflict there, but I am honestly not good enough at debugging to be certain.

[crash-2018-04-29_18.18.04-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1959385/crash-2018-04-29_18.18.04-server.txt)

P.S.  I posted this on a closed issue, not realizing it was closed...  Please disregard that post.

**Comment by AlexModGuy** [comment] 2018-06-15 03:55
dupe of #401

**Closed as completed by AlexModGuy** 2018-06-15 03:55 UTC
