### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by GSharkGamer** [Alex-the-666/Ice_and_Fire#4595] opened 2022-07-27 02:30 UTC
[Lately,] I've been having crashes related to the iceandfiremod where entities are occasionally crashing my game, I thought it fixed but now its currently related to the Stymphalian Bird from what I assume, but I do not know the current problem

[Problem Iceandfire.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9194531/Problem.Iceandfire.txt)

Here is the crashlog (I apologize if it doesn't work, this is my first time trying this)

**Comment by TheBv** [comment] 2022-08-23 17:28
Can't seem to replicate this. Most likely caused by another mod that is using a mixin. (Meaning a mod that can change the behavior of mobs from different mods)
Otherwise make sure that the ice and fire install isn't corrupt. 
Closing for now.

**Closed as completed by TheBv** 2022-08-23 17:28 UTC
