### ISSUE TITLE
 Female dragons never open their mouth

### ISSUE THREAD

**Issue by Spinogaming** [Alex-the-666/Ice_and_Fire#2137] opened 2020-01-30 17:00 UTC
Ice dragon wing attack doesn't do any damage
Female dragons never open their mouth
Dragons still split in half even with the fix turned on, only when grabbing something though (or maybe this is just for me)

**Comment by AlexModGuy** [comment] 2020-01-30 19:33
dupe of #1932 and fixed the second part.

**Comment by QuerrixTU** [comment] 2020-02-03 15:07
When i saw the title, my mind think other thing xD

**Closed as completed** 2021-02-25 21:44 UTC
