### ISSUE TITLE
Iceandfire2.1.10 With TerraForged MOD Crash

### ISSUE THREAD

**Issue by Accidey** [Alex-the-666/Ice_and_Fire#4602] opened 2022-07-30 12:55 UTC
[crash-2022-07-30_20.29.39-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9226478/crash-2022-07-30_20.29.39-client.txt)
When I use TerraForged MOD With IceAndFire MOD The Game Has a Certain Probability Of Crashing.

**Comment by Hjaldar** [comment] 2022-07-31 08:43
Looks like a duplicate of https://github.com/Alex-the-666/Ice_and_Fire/issues/4547

There is a fix at the linked issue

**Comment by Accidey** [comment] 2022-07-31 11:10
>
[crash-2022-07-31_19.04.18-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9228720/crash-2022-07-31_19.04.18-server.txt)
I updated the snapshot and it still crashes when I play<(。_。)>

**Comment by HendersonT** [comment] 2022-07-31 19:27
Same issue.
[crash-2022-07-31_14.21.29-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9229577/crash-2022-07-31_14.21.29-server.txt)

**Comment by TheBv** [comment] 2022-09-17 14:14
Fixed in 2.1.11

**Closed as completed by TheBv** 2022-09-17 14:14 UTC
