### ISSUE TITLE
[Bug]: Deformed chunk generation in existing worlds

### ISSUE THREAD

**Issue by LifelessAmir** [Alex-the-666/Ice_and_Fire#5134] opened 2024-01-29 09:00 UTC
### What happened?

When installed ice and fire in an existing world and tried generating new chunks, it seems to be getting deformed or sorta not connect to the already existing chunks which leaves behind gigantic deformed mountains and such in the world like the picture below.
![2024-01-28_23 31 24](https://github.com/AlexModGuy/Ice_and_Fire/assets/144461034/a5aacb3a-55c0-4ae9-9bf1-e2b4f54284c3)

### Minecraft Version

1.19

### Ice and Fire version

1.19.2-2.1.13-beta-3

### Citadel version

2.1.4-1.19

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment] 2024-01-29 09:09
iceandfire does not touch world gen (apart from structures/features which do not cause this issue)

**Comment by DigitalWendigo** [comment] 2024-02-02 11:04
Provide a log file and mods list, it's likely that another mod is causing the issue.

**Comment by TheBv** [comment] 2024-02-04 15:20
Besides that isn't this expected behaviour from minecraft whenever the world gen changed? E.g when upgrading from different versions of minecraft.
I'll close this for now I doubt this is a iaf issue.

**Closed as not planned by TheBv** 2024-02-04 15:20 UTC
Labels: bug, 1.19

**Comment by norfaremc** [comment] 2024-02-07 06:44
Confirmed in 1.19.2… when I generated the world normally, everything was spawning underground. As soon as I add ice and fire, dungeons from all mods started spawning above ground. I was told by one of my staff that this is a “long time complaint from many players about the ice and fire mod”…. I’ve been told by multiple players this has been an issue specifically with this mod for a long time. I really don’t know what causes it at all, but it’s confirmed to only happen when ice and fire is installed.

**Comment by SiverDX** [comment] 2024-02-07 06:56
yeah big X to doubt here

affecting structures / worldgen from other mods would require some very specific code that does not exist
personally I also have not seen this issue myself in a very big modpack (with a LOT of structure mods)

Considering the lack of mass reports (which would definitely happen if this mod causes such bugs on the regular) I tend to lean on the side of you having a very specific mod having this issue which might be self-caused due to other factors
