### ISSUE TITLE
Underground dragon nests are broken [2.1.6]

### ISSUE THREAD

**Issue by TheYoloPanda** [Alex-the-666/Ice_and_Fire#3913] opened 2021-05-28 15:31 UTC
The interior of the underground dragon nests is almost always broken. For broken i mean there are chunks that didn't generate correctly near the nests

1. Generate a new world
2. Set yourself in a spectator mode
3. Look for an underground dragon nest
4. It will be probably broken like the images

Images:
1)- https://imgur.com/qwSJAUP
2)- https://imgur.com/ExUtgtM

I did some tests, first i tried generating some new world and see if not only mine was bugged, all the worlds i generated had the same error on all underground dragon nests.
At that point I thought that it could be a bug caused by some mod that modifies the generation of the caves such as the quark and so I created a new instance with nothing but the "Ice and Fire: Dragons" v2.1.6 and the "Citadel "and the bug is still there. So it's not due to some other mod that breaks the generation of underground dragon nests.
Image of the undergound dragon nest with only IaF and Citadel installed: https://imgur.com/ZJviNef

**Comment by Lashriel** [comment] 2021-06-11 10:04
I *think* this is a vanilla chunk-generation issue. Not sure if it can be fixed within Ice&Fire.

**Comment by User-green** [comment] 2021-07-09 07:12
Update mod to 2.1.7+.

**Comment by Skydragonsz** [comment] 2021-10-24 18:35
It's still has problems in 2.1.9
Same problem as #3720

![image](https://user-images.githubusercontent.com/1357800/138607862-be0cf907-bc05-4df6-ba3f-1a827ce66ff5.png)

**Comment by TheBv** [comment] 2022-04-26 17:32
Closing as it's a duplicate of #3720

**Closed as completed by TheBv** 2022-04-26 17:32 UTC
