### ISSUE TITLE
Issues with YAWP "Yet Another World Protector" 1.18.2

### ISSUE THREAD

**Issue by Hati-GPT** [Alex-the-666/Ice_and_Fire#4797] opened 2023-03-17 23:37 UTC
So it seems ice and fire disables some commands from YAWP and other mods making some of the other mods entierly obsolete. So it kinda rolls down to go without ice and fire or go without spawn protection, might want to fix that whatever the issue may be,

**Comment by Z0rdak** [comment] 2023-03-27 18:51
Can confirm this (I am the dev of YAWP). Just wanted to give some extra info here:

# Description

When loading my mod [YAWP](https://www.curseforge.com/minecraft/mc-mods/yawp) together with Ice and Fire, commands of my mod are not being registered at all. It is unusable this way.

Do you know why this could be the case? This does not happen with any other mod than Ice and Fire. Let me know if you need any other informations.

My mod either uses `/wp ...` or `/yawp ...` for registering the commands depending on the configuration.

Thanks in advance - hope to get a response. :)

Best regards
Z0rdak

# Versions to reproduce the issue

- **Forge**: 1.18.2 - 40.2.1
- **Ice & Fire**: iceandfire-2.1.12-1.18.2-beta.jar
- **YAWP**: yawp-1.18.2-0.0.2.6-beta4.jar

1. Add the mods 
2. start the server

## Expected

- Both mods are loaded and working without any problems. 
- `/wp ...` or `/yawp ...` can be used to manage YAWP regions.

## Actual

The commands for YAWP are not registered, rendering the mod non-functional.

**Comment by TheBv** [comment] 2023-03-31 01:51
Ice and fire dynamically creates a datapack based on json configs.
To load this datapack it needs to reload every resource so it does the same thing the `/reload` command does.
I've tested this with just YAWP installed and running `/reload` seems to unregister every command.

**Comment by Z0rdak** [comment] 2023-03-31 06:02
Thanks for the heads-up! 👍  
I've just tested it myself. The command auto-completion/suggestion is still intact, but the commands are no longer registered/working.

That sounds very like a me-problem, then.  
I didn't know the `/reload` command could cause this. I didn't even know it could mess with already registered commands.

You seem to know exactly where to look for this issue. Any ideas why/how this could happen?

Edit: At which time in the mod-loading cycle does Ice & Fire trigger the reload? Maybe I can register my commands afterward.

**Comment by TheBv** [comment] 2023-03-31 11:52
You are already subscribed to `net.minecraftforge.event#RegisterCommandsEvent`
I myself haven't worked with commands but from the short docstring on that it seems to me that you need to re-register the commands every time the event gets triggered. 
I assume you put it in the config Event because forge triggers those quite late. I've had to deal with this a lot as well.
And from my experience the forge team really doesn't want you to get around those restrictions.
Best idea I have right now is just to keep things as is but to add a check if the `CommandPermissionConfig` has been `initialized` so to speak; and if it has you can just register the commands with the same config values every time the `RegisterCommandsEvent` is triggered.
It's janky - you might find a better solution, but it's sadly what you have to do a lot of times when you want to modify anything with config files, besides values that get referred to mid game.

**Comment by Z0rdak** [comment] 2023-03-31 16:16
First of all: Thank you for helping me. 
I really appreciate it! Especially since this is not your problem but my. You even dug through my code to give me an answer. :)

I agree with you, it's kind a _janky_, but it will have to do for a workaround. I'll try it out.

Thanks again!

Feel free to close the issue :+1:

**Comment by TheBv** [comment] 2023-03-31 19:20
I'll keep this post up until it has been fully resolved. Mostly to avoid duplicates. :)

**Comment by Z0rdak** [comment] 2023-04-15 21:38
Hey there. Just a heads up that this is now resolved with the latest version of YAWP (**0.0.2.8-beta1**).

**Closed as completed** 2023-04-17 18:52 UTC
Labels: 1.18
