### ISSUE TITLE
Ice and Fire mobs endlessly spawn.

### ISSUE THREAD

**Issue by Romoslayer** [Alex-the-666/Ice_and_Fire#4444] opened 2022-04-15 18:23 UTC
https://github.com/Alex-the-666/Ice_and_Fire/issues/4368
Literally the same as this except it's happening for more mobs now (they don't stop spawning).

**Comment by DigitalWendigo** [comment] 2022-04-27 09:33
Have you tried fiddling with Citadel's config file for increased spawns per chunk?
Try lowering, or disabling that feature, and see if the issue still persists. 
Also maybe list any mobs you're using that alter spawning in any way or form, including your performance mods.

**Comment by DigitalWendigo** [comment] 2022-05-10 17:30
This can probably be closed as it's the same issue as mentioned in #4368 
It's caused by another mod.

**Closed as completed** 2022-05-10 17:56 UTC
