### ISSUE TITLE
[Bug]: Armor bug with OptiFine

### ISSUE THREAD

**Issue by Fowren** [Alex-the-666/Ice_and_Fire#5040] opened 2023-12-11 23:29 UTC
### What happened?

![WhatsApp Image 2023-12-11 at 20 23 11](https://github.com/AlexModGuy/Ice_and_Fire/assets/153565791/01c5712d-51a7-4f94-9e4b-eb35b7f409ab)
the armor texture is all messed up when using optifine, I tested all versions of optifine and all alpha versions of the mod for 1.20.1 and the texture of all armor (except the sheep's disguise and myrmex armor) always stays messy.

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-7

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Fowren** [comment] 2023-12-11 23:31
and yeah, when I don't use optifine the textures are normal

**Comment by SiverDX** [comment] 2023-12-11 23:32
thats just on optifine being omega intrusive
there are alternative mods which are more compatible
embeddium + oculus for rendering performance and shaders for example

**Comment by WilPermenter** [comment] 2023-12-12 02:07
I think this is a known issue, Its not OptiFine Specific as I am using oculus and having the same issues.

**Comment by SiverDX** [comment] 2023-12-12 06:53
¯\\_(ツ)_/¯

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/22003703/ebd42a1a-75a8-4d7e-b50e-0ad203f7267f)

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/22003703/3403af48-cfe8-4574-a850-f4c965910acb)

**Comment by TheBv** [comment] 2023-12-22 09:47
Might have to do with the armor layers at least to some extend. I've talked to Alex about this a bit and we didn't really arrive at a conclusion since he wants the armors to be as "tight"/close to the characters as they are currently.
Default minecraft armor is a lot more bulky hence it doesn't have that issue.

**Comment by SammieJay** [comment] 2023-12-30 21:32
> Might have to do with the armor layers at least to some extend. I've talked to Alex about this a bit and we didn't really arrive at a conclusion since he wants the armors to be as "tight"/close to the characters as they are currently. Default minecraft armor is a lot more bulky hence it doesn't have that issue.

Since this seems to be a design decision, I wanna look into porting the older bulkier textures to 1.18.2 by making a texture pack. Would that be easy to do? (I have little experience with making texture/resource packs but decent programming experience). And is there anywhere I can get access to the older Armor textures?

**Comment by TheBv** [comment] 2024-01-03 12:30
Duplicate of #4936

**Closed as not planned by TheBv** 2024-01-03 12:30 UTC
Labels: bug

**Comment by Kondr654321** [comment] 2024-07-21 12:20
А если проблемы с Oculus+emdeddium или+Rubidium и игра вылетает?

**Comment by Asuryan2001** [comment] 2024-11-03 13:37
> Duplicate of #4936

This is not the same bug. The one you're talking about is avout skin layers and is now patched. The bug described above is the texture not correctly used like the part of the texture image for the helmet being used for the leggings. It looks like Optifine is overwritting the json model files for the mod armors
