### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aiakos13** [Alex-the-666/Ice_and_Fire#4462] opened 2022-04-30 08:14 UTC
- I opened a server from a site called aternos. I've been playing with my friend for a week. There were some errors this morning and the server wrote: change or delete my ice and fire mod version, I've tried all versions, it's still broken and I don't want to delete it. I wrote to Aternos help, contact the founder of ice and fire mod, they said maybe they will help.

**server all diary:**
https://mclo.gs/ls6zgEX
**crash raport:**
https://mclo.gs/SBub1wI

**Comment by DigitalWendigo** [comment] 2022-04-30 09:16
Some things to note here for anyone that reads this issue.
The poster of this issue has combined three different mod packs together and has altered the contents of the modpack to their own liking. 
This might be the cause of the issue and therefor they are suggested to take the issue to the modpack author(s) to figure out what the problem is. 
Obviously modpacks shouldn't be combined willy nilly as this'll cause duplicates and issues unless you know what youre doing and have removed the duplicates. 
Meaning, the issue is probably not even an Ice and Fire issue directly. 

The packs used by this person are:

all the magic https://www.curseforge.com/minecraft/modpacks/all-the-magic-spellbound

craft soul https://www.curseforge.com/minecraft/modpacks/craft-souls#:~:text=Inspired%20by%20FromSoftware's%20amazing%20Dark,feel%20of%20the%20original%20game.

dark souls simulator https://www.curseforge.com/minecraft/modpacks/dark-souls-simulator

adventure and dungeons  https://www.curseforge.com/minecraft/modpacks/adventures-and-dungeons-a-d

If a moderator would be so kind as to add the appropriate lables, that would be appreciated.

**Comment by DigitalWendigo** [comment] 2022-05-02 19:02
I'm pretty sure this issue can be safely closed. 
Ice and fire works fine on its own, and the several modpacks thrown together are more than likely the issue.

**Comment by TheBv** [comment] 2022-05-02 19:11
Seems to be an issue with `allthemodium` or rather most likely the lack of the mod. Definitely not an Ice and Fire issue and it's also a mixin issue; closing.

**Closed as completed by TheBv** 2022-05-02 19:11 UTC
