### ISSUE TITLE
Client freezing/soft crash

### ISSUE THREAD

**Issue by orionSquared** [Alex-the-666/Ice_and_Fire#287] opened 2017-07-09 02:37 UTC
A few of us have noticed that when playing with this mod in a modpack (two separate packs), in single player worlds, that sometimes when we are near a world-gen dragon nest thing, we seem to lose the TPS. Suddenly TheOneProbe just keeps saying "waiting for server" and we can't interact with anything and nothing drops when we break it. When we try to log off of the single player worlds, the client freezes and we have to force quit.

This has been tried on both a Mac and a PC. Multiple players are experiencing the same issue. It seems to be intermittent on which nest it happens in, as I visited half a dozen, or so, in my most recent single player world and only 2 of them caused this issue. 

I can provide more details if you need any more information.

Thanks!

**Comment by EvilDylan** [comment] 2017-07-09 19:15
I can confirm, I've been having this issue as well and have been repeatedly testing with less mods and different config options, in preperation for opening my own issue (now unnecessary.)
For me this exact hangup happens randomly when (from my observations) a dragon is nearby and interacting in some way (flying, breaking blocks, fighting,) but I couldn't get it consistent enough for reliable reproduction aside from standing around a nest for a while.

latest.log provides no information aside from saying the game is running behind.
Increasing my RAM allowance from 3GB to 4GB seemed to improved the behavior, but the hangups still happen regardless.

**Comment by VallenFrostweaver** [comment] 2017-07-11 13:00
I'm getting the same issue. Just flying around in creative and seeing dragons or spawning them in I randomly will start with the permanent lag freeze (my attempt at labeling it with a name). Mobs will stop moving. I can move but not generate new chunks or further than my view distance without seeing anything beyond where I was when it started. Essentially the game gets frozen like in a big lag spike circle (i.e. flying dragon still flaps wings but doesn't move). Memory usage is fluctuating super fast from around 10% to 50% for me and FPS is like nothing happened and acts normally. I can't interact with anything anymore either. I had allocated 5.1Gb to memory. One last strange thing is the day/night cycles appears to also continue.  This has happened each time I've gone in to mess around with this mod. Exiting Minecraft will result in a "not responding" blank screen and it sitting there until I use task manager to close it and it won't generate a crash log.

**Comment by Oxameter** [comment] 2017-07-13 00:27
10GB allocated here. First noticed this on my server where we were all very excited to try out the mod that whenever we'd head near a nest and see a dragon, the world would stop being able to load chunks and then the server would lock up and not accept any commands, before finally crashing. Crash report was with the dragon's AI, I can probably post it if needed. I just tested on singleplayer and no crash occurs here, just a total game freeze where I can move around and break blocks but can't really do anything else, like everyone else. The dragon in this case was floating midair with a fire orb near its mouth, as if the lock up happened just when it shot it.

**Comment by ThatsMyLive** [comment] 2017-07-15 10:17
Take a look here, most likely the issue and until Version 1.2.0 you can turn the advanced dragon AI off and it will work again:
https://github.com/Alex-the-666/Ice_and_Fire/issues/266

**Comment by darkshadow543** [comment] 2017-08-06 22:05
I'm a pack developer and was testing when this happened to me.  So it is the dragons, or maybe because its on peaceful.

**Comment by darthvader45** [comment] 2017-08-18 18:50
Same issue here.  Really wish they'd manage to work out the issues and get 1.2.0 out soon.  I'm sick of this bug, as well as temp workarounds.

**Comment by AlexModGuy** [comment] 2017-09-05 02:22
Should be fixed in 1.2.0

**Closed as completed by AlexModGuy** 2017-09-05 02:22 UTC
