### ISSUE TITLE
Dragon Armor issue

### ISSUE THREAD

**Issue by Daniel190403** [Alex-the-666/Ice_and_Fire#4213] opened 2021-09-16 11:03 UTC
Dragon Armor does not add extra armor to a maxed out Dragon. Also the Dragonarmor can not give a Dragon more than 30 armor points.

![2021-09-16_13 00 40](https://user-images.githubusercontent.com/90551683/133600855-da121a10-ecd9-4eaa-abab-023210ec0746.png)

![2021-09-16_13 02 39](https://user-images.githubusercontent.com/90551683/133600999-89c2d157-fcb1-4bc1-8515-d9adc9800d9c.png)

**Comment by FlameyFaucet** [comment] 2021-09-16 11:05
This is normal. Dragons have armor limits, i assume to avoid ludicrously resilient dragons. They’re already tough at stage 5 anyway.

**Comment by Daniel190403** [comment] 2021-09-16 11:09
But i guess, it is not normal, that a armored maxed out dragon has less armor points that a smaller armored one

**Comment by FlameyFaucet** [comment] 2021-09-16 12:33
Hmm, might be an issue on that part then.  Minecraft has trouble with powerful armor on players, so it might be happening here.

**Comment by TheBv** [comment] 2022-05-19 01:13
Partial duplicate of #4054
Other issue is a limitation enforced by minecraft itself

**Closed as completed by TheBv** 2022-05-19 01:13 UTC
