### ISSUE TITLE
Invalid move player packet

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1885] opened 2019-09-30 07:16 UTC
Online multiplayer server tested.
When being picked up/bitten by a dragon, have begun getting kicked with the message being 

> Invalid move player packet

This is what was grabbed from the server-side.

> [02:41:06] [Server thread/WARN] [Sponge]: No entity type is registered for class com.github.alexthe666.iceandfire.entity.EntityMutlipartPart
[02:41:24] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 8089ms behind, skipping 161 tick(s)
[02:45:34] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Torpoon lost connection: Invalid move player packet received
[02:45:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Torpoon left the game

Doesn't seem to be an isolated issue either, as I've seen complaints on the CurseForge page as well by other users, whom I have no contact or relation with.

**Comment by morhavoc** [comment] 2019-10-18 14:37
Also experiencing this same error any time I ride a hippogryph. I was once able to ride it for a while, but after dismounting, I sort of fell through the world and got kicked with "Invalid player move packet" message.

Currently playing FTB Interactions (plus a few mods), experienced both on mod versions 1.8.0 and 1.7.1.

**Comment by Keltas** [comment] 2019-12-03 15:33
I got the same error when riding a hippogryph. After going thourgh my mod list I have identified it as a problem with Thaumic Arcana mod in my case. I've checked that mods issues page and found they have an open issue for it: https://github.com/Frontrider/thaumic_arcana/issues/73

**Comment by RaspyPiStyLiS** [comment] 2020-01-03 08:29
Also experiencing this bug, I manage a server and a player encountered it and I checked NBT data to find out the X and Z axis on their position data was NaN. Probably some bad math that divided by 0 at some point.

**Comment by AlexModGuy** [comment] 2020-01-30 05:30
fixed in 1.8.4

**Closed as completed by AlexModGuy** 2020-01-30 05:30 UTC

**Comment by morhavoc** [comment] 2020-02-05 05:43
I just updated to 1.8.4 and tried to ride a hippogryph, and unfortunately, it does not appear to be fixed. I experienced exactly the same issue.

Edit: Nevermind, this appears to be caused by Thaumic Arcana, not Ice and Fire.
