### ISSUE TITLE
crash when mausoleum spawners activate [2.1.9 1.16.5]

### ISSUE THREAD

**Issue by Niwdog** [Alex-the-666/Ice_and_Fire#4543] opened 2022-06-29 20:56 UTC
Describe the bug
Anytime you approach the mausoleum and the spawners activate the game crashes

To Reproduce
1. Start new world
2. Approach mausoleum
3. Game crashes

Expected behavior
It not Crash

Note
I know this is a problem with the spawners is because of the Exit log and when I go into spectator mode the spawners are not working, but when you go into survival or creative they do work

Exit code:
The game crashed whilst ticking block entity
Error: java.lang.ClassCastException: com.github.alexthe666.iceandfire.entity.tile.TileEntityDreadSpawner cannot be cast to net.minecraft.tileentity.MobSpawnerTileEntity
Exit Code: -1

**Comment by TheBv** [comment] 2022-07-03 00:59
Should be fixed with 2.1.10 also never was a Iaf issue. Most of the time it was caused by another allowing the behavior of mob spawners to be modified.

**Closed as completed by TheBv** 2022-07-03 00:59 UTC
