### ISSUE TITLE
server crash with 1.4.0-1.12.2 

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [Alex-the-666/Ice_and_Fire#655] opened 2018-04-26 20:10 UTC
when spawning a picie the server crashs.
for details see crashlog: [crashlog](https://gist.github.com/5t0rmr1d3r/2a465a33e28c05f9b0e9bdcdf061518a)

**Comment by AlexModGuy** [comment] 2018-06-15 03:46
dupe of  #661

**Closed as completed by AlexModGuy** 2018-06-15 03:46 UTC
