### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by jcas15** [Alex-the-666/Ice_and_Fire#197] opened 2017-04-13 00:59 UTC
I downloaded the mod but a lot of the textures appear to be broken save for a few. Any idea what could be causing this or any way to fix it?

**Comment by SOL3675** [comment] 2017-04-19 08:35
Looks like same issue here.
#151

**Comment by Alex-the-666** [comment] 2017-04-20 00:17
Duplicate of #151

**Closed by Alex-the-666** 2017-04-20 00:17 UTC
