### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by RickBardock** [Alex-the-666/Ice_and_Fire#3872] opened 2021-05-15 18:16 UTC
when I try to hatch a black dragon egg, it only rotates in the rain, but when it thunders the egg disappears? the egg was admin spawned, any ideas? i'm on versions, iceandfire-2.1.6-1.16.4

**Comment by TheBv** [comment] 2022-05-14 20:30
Duplicate of #3809

**Closed as completed by TheBv** 2022-05-14 20:30 UTC
Labels: DragonEgg
