### ISSUE TITLE
Feature Placement Issue [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by ImExlow** [Alex-the-666/Ice_and_Fire#4594] opened 2022-07-26 15:20 UTC
**Describe the bug**
This issue crashes my 3rd party forge server after my girlfriend moved into a chuck last night. Anytime she joins the server goes down. I will be reporting this issue to Cooking For Blockheads as well.

Forge version: 1.16.5-36.2.39

Mod version: 2.1.10-1.16.5

Optifine is used client side, it is not used on the server. This report is coming from the server. 

[crash-2022-07-26_07.50.59-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9191055/crash-2022-07-26_07.50.59-server.txt)

**Comment by Hjaldar** [comment] 2022-07-31 08:37
Looks like a duplicate of https://github.com/Alex-the-666/Ice_and_Fire/issues/4567

There is a fix at the linked issue

**Closed as completed** 2022-08-23 17:26 UTC
