### ISSUE TITLE
All the mob's structures spawn set to false when creating server; none of the mobs or their structures spawn in overworld

### ISSUE THREAD

**Issue by theweisa** [Alex-the-666/Ice_and_Fire#3094] opened 2020-11-03 01:01 UTC
For some reason when creating a server, all the mob structure spawns for ice and fire are set to false right after spawn is initialized. After checking the world, none of the structures exist but the spawn eggs for mobs work. In the config file for ice and fire, all the mob spawns are set to true as well. Is there anyway I can resolve this issue?
![Screenshot (795)](https://user-images.githubusercontent.com/73861521/97935292-ff10f500-1d2c-11eb-9e5a-e4f6546ddb5d.png)

**Comment by Dimerite** [comment] 2020-11-03 20:51
Same problem in client mode/single player. Mod loads fine but no spawns, ore generation or structures. I only could find some flowers and random loot in dungeons (like silver and such).

Tested in both 1.16.4/1.16.3
Forge 35.0.1/34.1.42
Citadel 1.5.0/1.4.1
Ice and Fire 2.1.1

**Comment by Nathan0236** [comment] 2020-11-04 00:53
Same problem here, config says all spawns and generation are set to true, but comes up as false upon server initiation. 
Thought it might have been a conflict with other structure gen / biome gen mods, but I tried the mod (with citadel) by themselves and still nothing. 
![Capture](https://user-images.githubusercontent.com/38023947/98056591-6301fd80-1e94-11eb-9186-938206d8ad9a.PNG)

**Comment by Neko2n** [comment] 2020-11-06 09:01
Yup, I can confirm this. It's probably because the hook between the mod and the config file isn't working, but I don't know

**Comment by AlexModGuy** [comment] 2020-11-19 21:34
fixed in 2.1.2

**Closed as completed by AlexModGuy** 2020-11-19 21:34 UTC
