### ISSUE TITLE
Gorgon monument generated under water

### ISSUE THREAD

**Issue by GregSCooper2514** [Alex-the-666/Ice_and_Fire#2440] opened 2020-05-10 11:48 UTC
![Screenshot_2](https://user-images.githubusercontent.com/65116080/81498363-2ed6c700-92cd-11ea-9384-1803a7850090.jpg)

**Comment by PiggiesGoSqueal** [comment] 2020-05-16 21:00
I will note this is a duplicate of my report:
https://github.com/Alex-the-666/Ice_and_Fire/issues/2424

Although mine is half underwater and yours is fully.

Also for future reference I recommend providing the forge version you're using, the mod version, your latest.log, and debug.log to help the developer have a better understanding of what is wrong and how to replicate it. At least as far as I've seen, when people report something but provide no details on how to reproduce it, the bug isn't fixed.

**Closed as completed** 2021-02-25 21:43 UTC
