### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Njalsi** [Alex-the-666/Ice_and_Fire#3990] opened 2021-06-18 21:55 UTC
Not sure if this is in the other versions but in 1.16.5 the cockatrice can attack players in spectator mode. The player wont take any dmg however he/she will get the nausia effect

**Comment by Nedok** [comment] 2021-06-19 10:47
Duplicate of #3987?

**Closed as completed** 2022-05-02 10:49 UTC
