### ISSUE TITLE
Dragons disappearing

### ISSUE THREAD

**Issue by KiwiTheParakeet** [Alex-the-666/Ice_and_Fire#1556] opened 2019-05-07 23:14 UTC
I was battling a bronze dragon, wild, and it disappeared. It wasn't too close to dying but its health was low. It disappeared, completely, I have a map mod and the dragon's icon was gone too. This I thought was just a glitch and I ignored it, but it happened again when I was battling a green fire dragon.

**Comment by AlexModGuy** [comment] 2019-08-08 04:42
dupe of #709

**Closed as completed by AlexModGuy** 2019-08-08 04:42 UTC
