### ISSUE TITLE
Probably mod incompatibility

### ISSUE THREAD

**Issue by Rodas20007** [Alex-the-666/Ice_and_Fire#4893] opened 2023-06-04 10:22 UTC
I am trying to create a world on java minecraft 1.16.5 and everytime I add the ice and fire mod the game crashes as soon as the world starts generating (I ve tried removing the mod and creating a new world and it worked) , the same thing happens when I tried to create a server for me and my friends with the same modpack. Any help?
[crash-2023-06-04_10.35.21-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11645311/crash-2023-06-04_10.35.21-client.txt) The modpack includes:
abnormals_core-1.16.5-3.3.1.jar
AI-Improvements-1.16.5-0.5.0.jar
alexsmobs-1.12.1.jar
allthemodium-1.5.18-1.16.5-36.1.23.jar
alltheores-1.3.6-1.16.5-36.1.0.jar
appleskin-forge-mc1.16.x-2.4.0.jar
Aquaculture-1.16.5-2.1.23.jar
architectury-1.32.68.jar
ars_nouveau-1.16.5-1.25.10.jar
Artifacts-1.16.5-2.10.5.jar
BackTools-1.16.5-10.2.0.jar
BetterAdvancements-1.16.5-0.1.1.115.jar
BetterBurning-1.16.5-6.0.8.jar
biggerreactors-1.16.5-0.5.1.jar
BiomesOPlenty-1.16.5-13.1.0.488-universal.jar
Bookshelf-Forge-1.16.5-10.4.33.jar
Botania-1.16.5-420.3.jar
BotanyPots-1.16.5-7.1.41.jar
bountifulbaubles-1.16.5-0.1.0-forge.jar
BrandonsCore-1.16.5-3.0.15.248-universal.jar
bwncr-1.16.5-3.10.16.jar
carryon-1.16.5-1.15.6.24.jar
catalogue-1.6.1-1.16.5.jar
cavebiomeapi-1.16.5-1.4.2.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
ChunkNoGoByeBye-1.16.5-1.3.0.jar
citadel-1.8.1-1.16.5.jar
cloth-config-4.16.91-forge.jar
Clumps-6.0.0.28.jar
cobblegenrandomizer-1.16-5.1.2.jar
CodeChickenLib-1.16.5-4.0.7.445-universal.jar
compactmachines-4.0.0-beta.2.jar
configured-1.5.4-1.16.5.jar
connectivity-2.4-1.16.5.jar
constructionwand-1.16.5-2.6.jar
Controlling-7.0.0.29.jar
cookiecore-1.16.5-3.3.1-9c789ef.jar
corpse-1.16.5-1.0.7.jar
CosmeticArmorReworked-1.16.5-v5.jar
CraftingTweaks_1.16.5-12.2.1.jar
crashutilities-3.13.jar
create-mc1.16.5_v0.3.2g.jar
CTM-MC1.16.1-1.1.2.6.jar
Cucumber-1.16.5-4.1.12.jar
culinaryconstruct-forge-1.16.5-4.0.1.0.jar
curios-forge-1.16.5-4.1.0.0.jar
Cyclic-1.16.5-1.5.20.jar
darkerdepths-1.16.5-1.1.4.jar
DarkUtilities-1.16.5-8.0.14.jar
DefaultOptions_1.16.5-12.2.1.jar
Dice-1.16.5-1.2.0.jar
Draconic-Evolution-1.16.5-3.0.29.518-universal.jar
dummmmmmy-1.16.5-1.3.3.jar
DungeonCrawl-1.16.5-2.3.12.jar
eidolon-0.2.7.jar
elevatorid-1.16.5-1.7.13.jar
enchantedbookredesign-3.3-1.16.4.jar
EnderStorage-1.16.5-2.8.0.170-universal.jar
EnigmaticLegacy-2.11.12.jar
Exchangers-1.16.5-3.1.1.jar
expandability-2.0.1-forge.jar
extcaves-2.4.jar
FarmersDelight-1.16.5-0.6.0.jar
fastfurnaceminusreplacement-1.1-1.16.3.jar
FastLeafDecay-v25.2.jar
FastWorkbench-1.16.5-4.6.2.jar
ferritecore-2.1.1-forge.jar
FluxNetworks-1.16.5-6.2.1.14.jar
flywheel-1.16-0.2.5.jar
forbidden_arcanus-16.2.3.jar
geckolib-forge-1.16.5-3.0.106.jar
grappling_hook_mod-1.16.5-v13.jar
GunpowderLib-1.16.5-1.2.3.jar
HammerLib-1.16.5-16.4.32.jar
iceandfire-2.1.12-1.16.5.jar
iChunUtil-1.16.5-10.7.0.jar
industrial-foregoing-1.16.5-3.2.14.7-16.jar
inventorypets-1.16.5-2.0.15.jar
inventorysorter-1.16.1-18.1.0.jar
ironchest-1.16.5-11.2.21.jar
ironfurnaces-1.16.5-2.7.7.jar
Jade-1.16.4-2.8.3.jar
jei-1.16.5-7.8.0.1009.jar
journeymap-1.16.5-5.8.5p6.jar
lootr-1.16.5-0.2.17.48.jar
magicfeather-1.16.2-3.2.0.jar
mahoutsukai-1.16.5-v1.34.44.jar
Mantle-1.16.5-1.6.157.jar
mcjtylib-1.16-5.1.8.jar
Mekanism-1.16.5-10.1.2.457.jar
MekanismAdditions-1.16.5-10.1.2.457.jar
MekanismGenerators-1.16.5-10.1.2.457.jar
MekanismTools-1.16.5-10.1.2.457.jar
metalbarrels-1.16.5-3.4a.jar
mightyarchitect-mc1.16.3_v0.5.jar
Morpheus-1.16.5-4.2.70.jar
MouseTweaks-2.14-mc1.16.2.jar
MysticalAgriculture-1.16.5-4.2.6.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
nolakes-0.1-1.16.4.jar
occultism-1.16.5-1.29.1.jar
OpenLoader-1.16.5-9.0.3.jar
OptiFine_1.16.5_HD_U_G8.jar
OptiForge-MC1.16.5-0.5.7.jar
orcinusscaves-1.3.jar
OreTweaker-1.16.5-2.7.1.jar
overloadedarmorbar-5.1.0.jar
paintings-1.16.4-7.0.0.1.jar
Patchouli-1.16.4-53.3.jar
PathToDirt-1.2.0-mc1.16.x.jar
phosphophyllite-1.16.5-0.5.1.jar
pipez-1.16.5-1.2.17.jar
Placebo-1.16.5-4.7.1.jar
randomium-1.16.5-1.7.jar
refinedstorage-1.9.18.jar
reliquary-1.16.5-1.3.5.1124.jar
repurposed_structures_forge-3.4.7+1.16.5.jar
rftoolsbase-1.16-2.1.5.jar
rftoolsbuilder-1.16-3.1.11.jar
rftoolscontrol-1.16-4.0.18.jar
rftoolsdim-1.16-7.0.21.jar
rftoolspower-1.16-3.0.14.jar
rftoolsstorage-1.16-2.0.19.jar
rftoolsutility-1.16-3.1.16.jar
rhino-forge-1605.1.5-build.75.jar
Scorge-3.1.3.jar
selene-1.16.5-1.9.0.jar
shutupexperimentalsettings-1.0.3.jar
silent-gear-1.16.5-2.6.36.jar
silent-lib-1.16.5-4.10.0.jar
skin_changer-0.2.2.jar
SolarFluxReborn-1.16.5-16.4.10.jar
sophisticatedbackpacks-1.16.5-3.15.20.755.jar
SoundFilters-0.14_for_1.16.2.jar
spark-1.9.1-forge.jar
SpawnerFix-1.16.2-1.0.0.2.jar
StorageDrawers-1.16.3-8.5.2.jar
strawgolem-1.16-1.9.jar
structurescompass-1.16.5-1.4.0.jar
supplementaries-1.16.5-0.18.5.jar
titanium-1.16.5-3.2.8.7-22.jar
toms_storage-1.2.19.jar
valhelsia_core-16.0.15.jar
VampiresNeedUmbrellas-1.16.5-1.1.5.jar
Vampirism-1.16.5-1.9.6.jar
Waystones_1.16.5-7.6.4.jar
worldshape-1.0.jar

**Comment by TheBv** [comment] 2023-06-07 19:24
Duplicate of #4811

**Closed as completed by TheBv** 2023-06-07 19:24 UTC
