### ISSUE TITLE
 tamed dragons taking damage on natural growth tick? [ICE AND FIRE 2.1.6]

### ISSUE THREAD

**Issue by Nightsol** [Alex-the-666/Ice_and_Fire#3632] opened 2021-02-28 16:20 UTC
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
So I've seen this bug posted on earlier versions, and i myself was running version 2.1.5 before updating today. the problem persisted between updating, hence the bug post. i have had this had this happen to every dragon I've raise from hatching, one of which died due to the "stuck damage". they take seemingly random damage from nothing, no mobs nor other entities in the same general location. not always, but occasionally this damage with warp the dragon into some nearby open areas, like caves or small open spaces, which is what I believe the stuck damage line comes from, from suffocating in a wall. This seems to happen to Stage 1 or Stage 2 dragons more frequently, it may potentially happen to stage 3 or beyond as well. it does not happen when feeding them Dragon Meal.

**To Reproduce**
1. Spawn a dragon of any type (i have only had this happen with Ice and Lightning Dragons myself, but I assume it would effect the Fire ones as well.)
2. Watch them as they sleep, that is when I've seen the damage happen exclusively.
3. keep a summoning crystal for that dragon in case they warp from the damage, that's how I've been saving them/calling them back. 

**Expected behavior**
Dragon doesn't take damage from seemingly nothing, or from a natural growth tick? 

**Screenshots**
Moved my two lightning dragons together for this screenshot, both are Stage 2, could not get a screencap of them taking the damage. it doesn't matter if they are close to the edge or in the center of the room. this room is at 60 y level.
![2021-02-28_10 17 30](https://user-images.githubusercontent.com/79799570/109425192-257e2e80-79b5-11eb-9d38-70265077125d.png)

**Additional context**
here is the list of mods i am running alongside Ice and Fire, as well as the Forge Version. perhaps one of those could be causing the bug?

Useful Backpacks
Structurize
U Team Core
Minecolonies
Valhelsia Structure
Spartan Weaponry
JustEnoughItems
ProjectE
Forge: Version 36.0.42
Spartan Shields
Overloaded Armor Bar
Waystones
Forge Endertech
Large Ore Deposits
Gravestone mod
Clumps
Iron Chests
Citadel

**Comment by fallenthereaper** [comment] 2021-02-28 17:04
I have the same issue

**Comment by TheBv** [comment] 2021-03-03 18:29
Thanks for all the information! Makes it a lot easier to look for the root cause of the issue!
This does seem to be a duplicate of #3606 though.

**Closed as completed** 2021-03-12 21:20 UTC
