### ISSUE TITLE
legendary weapon,myrmex colony,makes much lags

### ISSUE THREAD

**Issue by guide-for-you** [Alex-the-666/Ice_and_Fire#1699] opened 2019-08-10 16:08 UTC
When I used this weapon minions appearing makes much lags that may crash world.

**Comment by BugmanBugman** [comment] 2019-08-10 16:09
Clarification? What are your specs?

**Comment by guide-for-you** [comment] 2019-08-10 16:11
I edited this.

**Comment by BugmanBugman** [comment] 2019-08-10 16:14
can we get your specs.

It’s a weapon that spawns enemy, maybe it might be too much for your rig.

**Comment by guide-for-you** [comment] 2019-08-10 16:23
My computer can run the Witcher without any lags on average settings.
This weapon makes friendly flying myrmex(that have strange AI btw) on certain time that disapper after this time,but when you use this weapon in survival or creative it's makes much lags.

**Comment by SirAron111** [comment] 2019-08-10 16:37
Can confirm this have a 4k machine and it still lags like shit with the colony especially on summoning them and on the moment they start a targeting something. Maybe the Ai is looping or something.

**Comment by guide-for-you** [comment] 2019-08-10 19:09
Ahh,this thing works only for creativity and everything is ok in survival, and then I crashed only because of a conflict with two other mods.

**Comment by AlexModGuy** [comment] 2020-01-30 18:49
dupe of #2095 and #1449

**Closed as completed by AlexModGuy** 2020-01-30 18:49 UTC
