### ISSUE TITLE
game crash when contacting other mod[1.16.5]

### ISSUE THREAD

**Issue by hivjSiricnak** [Alex-the-666/Ice_and_Fire#4450] opened 2022-04-28 01:19 UTC
**Describe the bug**
When any Ice and Fire mob gets hit by an arrow or bee while the PierceArrow mod is in the game collapses.

**To Reproduce**
1. Hawe the Ice and Fire; PierceArrow mods installed.
2. Hawe a Ice and Fire mob shot it with a bow, hawe an aggressive one for this (Death worm) place next to it a bee and wait untill the bee hits back.
3. Game collapses.

**Expected behavior**
The arrow (or bee sting) stuck into the mob like when the player get hit by an arrow.

I mentioned it to the creator of the PierceArrow mod and I hope the creator of this mod will pick up the line with the creator of the PierceArrow mod and find a solution for the problem.

**Comment by DigitalWendigo** [comment] 2022-05-10 17:26
Please provide a full mod list, log file and crash log. 
Also, please try out the new Alpha version. It contains many big fixes and improvements. 
Chances are, the issue might be related to an old bug and has been fixed in the new version. 
https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/2.1.10-alpha2

**Comment by hivjSiricnak** [comment] 2022-05-10 21:29
Tomorrow I will trie it, and if it is still brakes I will provide the crash report. Thanks you :)

**Comment by hivjSiricnak** [comment] 2022-05-13 13:27
[crash-2022-05-13_15.04.33-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8687288/crash-2022-05-13_15.04.33-client.txt)
This is the crash report. I only had the version you sent and the Pierce Arrow downloaded. The creator the pierce arrowe mod sayd someting about "different modells" under it's mod on the curse site. The only way I see to fix this is to help out the other mod creator, but according to one of its comments I dont think the person want to work on the older versions.

**Comment by DigitalWendigo** [comment] 2022-05-13 13:34
Oh it says in the description that the 1.16 version is bugged with cashes. 
And if the original mod author doesn't want to do anything on their end and rather move on to the other mc versions then this bug might unfortunately not be fixable on IAF's end. 
I've run some tests in the meantime while waiting for your crash log and it seems like a bunch of other modded creatures also suffer from random crashes with Pierce Arrows installed. 
So it's not an IAF issue by itself.

**Comment by hivjSiricnak** [comment] 2022-05-13 15:30
At least thanks for the help and attention. :) It's a bit sad that the other mod's author don't want to work with the "older" wersions becose the programing difficulties. Whem I first saw the pierc arrow mod I instantly imagined how good would it look in a fight against a dragon, at the end it would have looked like a nail pillow filled with nails. :D Anyway thanks again and hawe a nice day. :)

**Comment by DigitalWendigo** [comment] 2022-05-13 15:39
Thank you, you as well!
Please close this issue as it's not caused by IAF.

**Closed as completed** 2022-05-13 16:14 UTC
