### ISSUE TITLE
[Bug]: Copper Armor visual bugs

### ISSUE THREAD

**Issue by InternationalPirate** [Alex-the-666/Ice_and_Fire#5151] opened 2024-02-05 06:57 UTC
### What happened?

Instances where copper armor doesn't render properly on the player model
![2024-02-04_23 37 23](https://github.com/AlexModGuy/Ice_and_Fire/assets/158996884/1e7c603e-fa89-4004-881a-e45b41d30f9f)
![2024-02-04_23 37 30](https://github.com/AlexModGuy/Ice_and_Fire/assets/158996884/aeaf64e9-5986-43fc-9c15-e2b574f3233c)
Image 1: wearing copper armor without the leggings makes your legs invisible
Image 2: copper armor doesn't render properly in the inventory

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-1.20.1-beta-2.jar

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment] 2024-02-13 19:44
Duplicate of #5112

**Closed as not planned by TheBv** 2024-02-13 19:44 UTC
Labels: bug, 1.20
