### ISSUE TITLE
Using a chain on a dragon then killing it will crash the game

### ISSUE THREAD

**Issue by wolf653** [Alex-the-666/Ice_and_Fire#2020] opened 2019-11-14 21:35 UTC
So yeah you cannot transport dragon corpses that way

**Comment by wolf653** [comment] 2019-11-14 22:03
crash log do note that my pc's keyboard appeared to glitch out constantly pressing enter i tried to correct the issue to make it easier to view
[crash-2019-11-14_13.31.57-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3848812/crash-2019-11-14_13.31.57-server.txt)

**Comment by AlexModGuy** [comment] 2020-01-30 19:28
This is a dupe of #401

**Closed as completed by AlexModGuy** 2020-01-30 19:28 UTC
