### ISSUE TITLE
[Bug]: Crash when mounting or being grabbed by Dragons (any type)

### ISSUE THREAD

**Issue by SamHubert** [Alex-the-666/Ice_and_Fire#4965] opened 2023-10-05 23:22 UTC
### What happened?

Crash Report: [crash-2023-10-05_16.26.01-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/12825503/crash-2023-10-05_16.26.01-client.txt)

Log File: [2023-10-05-3.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12825501/2023-10-05-3.log)

Whenever I mount a dragon of any kind (either by intentionally mounting a tamed dragon or by being grabbed by a wild one in combat,) my game crashes and throws the same error. I have attached a crash file, all crashes look identical but I can provide more if required. This does not happen with Ice and Fire alone, and is occurring in a rather large modpack, but I have narrowed it down to happening only when there is a mod that alters the players stats or health display in some way. Some examples include but don't appear to be limited to Health Overlay (Forge) and ExpandAbility. I am still testing with other mods. This ONLY happens with dragons as far as I am aware, but happens consistently. No other Ice and Fire mob has caused the same issue.

This also only crashes my client and not the dedicated server I am logging into. It crashes in single player worlds. This crash occurs on two different computers as well with identical mods and installation methods, but strangely a third person with whom I have been playing on the dedicated server with does not appear to be crashing this way, their mods and installation are also identical in every way I can fathom. I have also attempted re-installing everything from the modpack multiple times in case this was an error that happened due to a corrupted installation, but have had no success in fixing this.

I am sorry for being long-winded but please let me know if I can provide any more information, or if this is a problem for a different mod. I am not adept at reading stack traces and only have beginner Java knowledge.

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
[05Oct2023 16:25:49.319] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientPacketListener/]: Received passengers for unknown entity
[05Oct2023 16:25:49.320] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientPacketListener/]: Received passengers for unknown entity
[05Oct2023 16:25:49.889] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] [Server: Saved the game]
[05Oct2023 16:25:50.239] [Render thread/INFO] [mezz.jei.common.ingredients.IngredientManager/]: Ingredients are being removed at runtime: 11 net.minecraft.world.item.ItemStack
[05Oct2023 16:25:50.357] [Render thread/INFO] [hexal/]: loading everbook {macros:[],uuid:[I;-314167161,-822851182,-1800984729,-1136651173]} for ed463087-cef4-4992-94a7-2767bc40145b from C:\Users\Sam\curseforge\minecraft\Instances\Wizard City Modpack Testing (1)\everbook\everbook-ed463087-cef4-4992-94a7-2767bc40145b.dat
[05Oct2023 16:25:50.374] [Render thread/INFO] [Enigmatic Legacy/INFO]: Blue Skies detected: false
[05Oct2023 16:25:52.058] [Render thread/WARN] [journeymap/]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[05Oct2023 16:25:52.115] [Render thread/INFO] [journeymap/]: Custom modded block handling enabled for create
[05Oct2023 16:25:52.208] [Render thread/INFO] [journeymap/]: Loaded 2 waypoints from C:\Users\Sam\curseforge\minecraft\Instances\Wizard City Modpack Testing (1)\journeymap\data\mp\Minecraft~Server_26e5d9df~a7a5~4784~957d~a3bd7cd064c8\waypoints
[05Oct2023 16:25:52.218] [Render thread/INFO] [journeymap/]: Mapping started in C:\Users\Sam\curseforge\minecraft\Instances\Wizard City Modpack Testing (1)\journeymap\data\mp\Minecraft~Server_26e5d9df~a7a5~4784~957d~a3bd7cd064c8\overworld. Memory: 4272MB total, 1214MB free 
[05Oct2023 16:25:52.222] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] JourneyMap: Press [J]
[05Oct2023 16:25:52.225] [Render thread/INFO] [journeymap/]: 
[05Oct2023 16:25:52.527] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1419) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1225) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23255!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[05Oct2023 16:25:53.456] [Render thread/INFO] [hexal/]: saving everbook {macros:[],uuid:[I;-314167161,-822851182,-1800984729,-1136651173]} at C:\Users\Sam\curseforge\minecraft\Instances\Wizard City Modpack Testing (1)\everbook\everbook-ed463087-cef4-4992-94a7-2767bc40145b.dat
[05Oct2023 16:25:53.457] [Render thread/INFO] [configured/]: Unloading synced configs from server
[05Oct2023 16:25:53.458] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[05Oct2023 16:25:53.458] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[05Oct2023 16:25:53.458] [Render thread/INFO] [mezz.jei.forge.startup.ClientLifecycleHandler/]: Stopping JEI
[05Oct2023 16:25:53.484] [Render thread/INFO] [journeymap/]: Mapping halted in C:\Users\Sam\curseforge\minecraft\Instances\Wizard City Modpack Testing (1)\journeymap\data\mp\Minecraft~Server_26e5d9df~a7a5~4784~957d~a3bd7cd064c8\minecraft:overworld
[05Oct2023 16:26:01.963] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 7319963b-26b1-435a-8d1d-db7ac163fa2a
[05Oct2023 16:26:01.974] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 20c4f204-77d7-435b-880d-b7accddd0500
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by goldfinder** [comment] 2023-10-06 07:43
Whati can get from your information you have sent, it had a unreported exception, of the posestack.
> java.lang.IllegalStateException: Pose stack not empty

**Comment by SamHubert** [comment] 2023-10-06 14:45
Yeah I just can't quite figure out why or what is causing it. It's not an incompatibility between the mods mentioned even because I just put all of the "problematic" ones together that I had tested with in one install with nothing else and the crash is not happening. So some other mod in my modpack must be at fault. I don't know why it's so specifically causing problems with dragons from ice and fire, either. I can close this issue if need be though I am interested to see if anyone else has had a similar experience within the context of a larger modpack.

**Comment by onepieceluffyy** [comment] 2023-10-06 19:05
I think you’re just going to have to do the long and tedious task of removing the mods in batches and narrowing it down till you find the mod responsible. It ain’t fun but I’ve had to do this before myself, as I’m sure many others have. The log is complaining about rendering, so I would guess maybe flywheel, create and it’s addons? Try removing those and see if the crash happens.

Somewhat unrelated to your current issue, but I thought I should warn you that the current version of Ice and Fire for 1.18.2 seems to have major TPS lag issues when trying to ride dragons. I recommend downgrading to [beta 2](https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/2.1.12-beta-2)  in this GitHub’s releases tab. I’m guessing it’s caused by the new riding system they implemented after that.

**Comment by SamHubert** [comment] 2023-10-06 23:21
Oh for sure, I have been going through my modpack in batches for a couple of days now, and just when I think I find what's causing the issues, I put it into a profile with just ice and fire and it doesn't crash. Create and its addons don't seem to be crashing anything when isolated with ice and fire either u_u.

Thank you for the tip on Beta 2 though! I will keep testing and if I find anything else I'll post it here.

**Comment by bluelobster1** [comment] 2023-11-20 08:50
i am having the same issue except it doesnt crash in singleplayer worlds, if you have found a solution please let me know and thank you for making this report in the first place

**Comment by SamHubert** [comment] 2023-11-20 19:50
So, I'm not sure if it's honestly an issue with Ice and Fire at this point or if it's just a case of several things touching the way rendering works, and EVENTUALLY crashing. I actually had another friend join the modpack server with the exact same mods, and he didn't crash at all when he was grabbed by or mounting a dragon, but I would crash every single time either him OR I were grabbed by or mounted on a dragon. I also recently re-did some aspects of my modpack, and ice and fire dragons no longer throw a pose stack error, but werewolf transformations from "Werewolves - Become a Beast!" do. The modlist is incredibly similar, too. It just feels random or like it may be some obscure, happenstance forge or minecraft error. Also, when I have this issue, it happens in both singleplayer or external servers. Sorry I can't be more helpful, it's super frustrating. I am STILL to this day testing things, so I will post an update if I can pinpoint the exact issue.

**Comment by orangebongo** [comment] 2023-11-21 16:58
I'm hosting a server where we're experiencing very similar issues as described, except we get a different error than the pose stack one. The server seems to chug along fine but the clients that are close to a player who tries to mount a dragon immediately crash, and now we're stuck in a spot where the player who has mounted the dragon remains mounted as they join, and then immediately crash themselves and everyone around them.

I have some client logs from two different players who crashed, both at slightly different times. Hopefully they can help nail something down in addition to the above?

[firstclientcrash.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13428991/firstclientcrash.txt)
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13429106/latest.log)
[crash-2023-11-21_02.45.30-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13429002/crash-2023-11-21_02.45.30-client.txt)

It does definitely look like a client side error that is thrown on the rendering thread. The last crash log is definitely most interesting to me since it outright mentions the dragon being ticked and its passenger:

```
Stacktrace:
	at net.minecraftforge.common.util.LogicalSidedProvider.get(LogicalSidedProvider.java:47) ~[forge-1.18.2-40.2.9-universal.jar%23137!/:?] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.Pathfinding$IafThreadFactory.newThread(Pathfinding.java:91) ~[iceandfire-2.1.12-1.18.2.jar%2396!/:2.1.12-1.18.2] {re:classloading}
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:630) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1353) ~[?:?] {}
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[?:?] {re:computing_frames}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.PathResult.startJob(PathResult.java:170) ~[iceandfire-2.1.12-1.18.2.jar%2396!/:2.1.12-1.18.2] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.setPathJob(AdvancedPathNavigate.java:244) ~[iceandfire-2.1.12-1.18.2.jar%2396!/:2.1.12-1.18.2] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.moveToXYZ(AdvancedPathNavigate.java:386) ~[iceandfire-2.1.12-1.18.2.jar%2396!/:2.1.12-1.18.2] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.m_26519_(AdvancedPathNavigate.java:477) ~[iceandfire-2.1.12-1.18.2.jar%2396!/:2.1.12-1.18.2] {re:classloading}
	at net.mcreator.enlightened_end.procedures.PlayerRidingEverglintProcedure.execute(PlayerRidingEverglintProcedure.java:38) ~[enlightend-5.0.10-1.18.2.jar%2389!/:?] {re:classloading}
	at net.mcreator.enlightened_end.procedures.PlayerRidingEverglintProcedure.onPlayerTick(PlayerRidingEverglintProcedure.java:20) ~[enlightend-5.0.10-1.18.2.jar%2389!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_660_PlayerRidingEverglintProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:879) ~[forge-1.18.2-40.2.9-universal.jar%23137!/:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:279) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntity,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B}
	at net.minecraft.client.player.RemotePlayer.m_8119_(RemotePlayer.java:37) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.Entity.m_6083_(Entity.java:1698) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinEntity,pl:mixin:APP:railways-common.mixins.json:client.AccessorEntity,pl:mixin:APP:ars_nouveau.mixins.json:light.LightEntityMixin,pl:mixin:APP:beyond_earth.mixin.json:EntityTick,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinEntity,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:wthit.mixins.json:EntityAccess,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:sliceanddice.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6083_(LivingEntity.java:2688) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:beyond_earth.mixin.json:LivingEntityTickEnd,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:create_enchantment_industry.mixins.json:LivingEntityInvoker,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_6083_(Player.java:462) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntity,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_104641_(ClientLevel.java:236) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:226) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:beyond_earth.mixin.json:BlockSet,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:ice_dragon (com.github.alexthe666.iceandfire.entity.EntityIceDragon)
	Entity ID: 250426
	Entity Name: Ice Dragon
	Entity's Exact location: 273.50, 73.00, -334.50
	Entity's Block location: World: (273,73,-335), Section: (at 1,9,1 in 17,4,-21; chunk contains blocks 272,-64,-336 to 287,319,-321), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [RemotePlayer['Dizrawr'/250425, l='ClientLevel', x=273.50, y=78.22, z=-334.50]]
	Entity's Vehicle: null
	```

**Comment by bluelobster1** [comment] 2023-11-22 15:41
have you tried removing enlightend

**Comment by bluelobster1** [comment] 2023-11-22 23:43
alright i just tried and enlightend was the issue for us, something about net.mcreator.enlightened_end.procedures.PlayerRidingEverglintProcedure.execute(PlayerRidingEverglintProcedure.java:38) ~[enlightend-5.0.10-1.18.2.jar%2389!/:?] {re:classloading}
	at net.mcreator.enlightened_end.procedures.PlayerRidingEverglintProcedure.onPlayerTick(PlayerRidingEverglintProcedure.java:20) ~[enlightend-5.0.10-1.18.2.jar%2389!/:?] {re:classloading} 

was bugging out mc

**Comment by peetey897** [comment] 2023-11-23 19:47
I'm trying to work my way to the bottom of this. I'll update as soon as I have any info.

**Comment by peetey897** [comment] 2023-11-23 21:31
I did try removing enlightend, but to no avail.

So, here are the results of my attempt to solve this mystery. I've spent the morning doing a binary search to try and find the mod that was causing this crash. I disabled mods in roughly related chunks including large mods with addons such as Tinker's and RFTools, performance mods, and others. None of these resolved the issue. I was finally able to stop this crash from occurring when I disabled pretty much all mob-adding mods, including Alex's Mob's, Untamed Wilds, Exotic Birds, Frikinzi's Fauna, Upgrade Aquatic, Zoo Architect, and Goodall. I have a TON of wildlife mods as they're my favorite. This was the chunk of mods that finally stopped the crash.

I've slowly re-enabled each mod to replicate the issue and confirmed that the mod causing the problem for me is Alex's Delight.

Now, this doesn't make a whole lot of sense. I've been through all of the bug reports here that describe this or a similar issue, and collected all of the posted crashdumps, and distilled out lists of mods used by myself and everyone who is having this problem. The thing is, while the error message (pose stack) is the same across all reported crashes, the mod that seems to have been the culprit for me, Alex's Delight, is not on anyone else's modlist but mine. This leads me to believe that the mod causing this issue for each person is different.

It does make sense for Alex's Delight to be the problem, as it's a compat mod for Alex's Mobs, and Alex's Mobs is by the same mod author as Ice & Fire, so I am assuming that Alex's delight is touching something - probably something in Citadel - that's causing the issue.

However, since many others having this problem don't seem to have it installed, I'm not sure how helpful this will be.

All that said, if you have Alex's Delight installed, try removing it and see if it helps.

**Comment by bluelobster1** [comment] 2023-11-24 05:53
thing is we do have alex's delight, and that wasnt the issue for us as we still have it and we dont crash anymore, so it seems that the issue comes form one mod in a modpack that is different for anyone that is having the issue. how i found that it was enlightened end for us is that is was in the crash reports me and my friends were getting, so maybe just look at what mods come up in the crash reports every crash and see if removing it works. from the crash report of the op the one that i could see crashing it would be either flywheel or enhanced celestials because all the other mods ei: ars nouveau create supplementaries and quark use flywheel to help render some stuff in the world. enhanced celestials completely changes how the sky is rendered from what i remember so maybe try removing that one op

**Comment by SamHubert** [comment] 2023-11-24 17:53
I also have Alex's Delight in the revised version of my modpack, and have not had a crash yet regarding the dragons. Flywheel/Create, Enhanced Celestials, and Ars Nouveau are all working well together in this pack. Notably I no longer have Quark or Supplementaries, but when I did my testing those two weren't a problem, either. The mods that "caused problems" in the pack were Health Overlay (Forge), ExpandAbility, and Hexerei, and Inventory Hud+ But none of these caused problems when installed alone with Ice and Fire at all. I'm still currently having the same problem happen now with a completely different mod which I'll have to start testing with, but right now the dragons are working.

**Comment by TryingMyBestt** [comment] 2023-11-26 21:01
I'm not sure if you have it but I belive epic fight mod was the issue for me, especialy when combined with improvedmobs mod.

**Comment by TheBv** [comment] 2023-12-25 22:32
This is one of those crash logs related to rendering where you just can't make out any mod that's responsible.
Per se it doesn't even list ice and fire as the mod causing the crash, although I can believe it being a common variable together with some other mods.
I'll close this since you can't efficiently trouble shoot these issues and I therefor don't have the time.

**Closed as completed by TheBv** 2023-12-25 22:32 UTC
Labels: bug, Other Mod Causes This, Not able to replicate, 1.18

**Comment by MageOfGaming** [comment] 2024-08-18 12:55
> Yeah I just can't quite figure out why or what is causing it. It's not an incompatibility between the mods mentioned even because I just put all of the "problematic" ones together that I had tested with in one install with nothing else and the crash is not happening. So some other mod in my modpack must be at fault. I don't know why it's so specifically causing problems with dragons from ice and fire, either. I can close this issue if need be though I am interested to see if anyone else has had a similar experience within the context of a larger modpack.

Same issue in 1.18.2 here made a comment about this here; https://github.com/AlexModGuy/Ice_and_Fire/issues/5100#issuecomment-2295253016
