### ISSUE TITLE
[Bug]: Armor clips through skins that have second layer

### ISSUE THREAD

**Issue by GhostLupine** [Alex-the-666/Ice_and_Fire#5054] opened 2023-12-29 04:44 UTC
### What happened?

So, the armor sets in this mod do not look great with skins that have a second layer to them. I did see someone else discussed this earlier back in October, but I do feel the need to mention it again in case it was forgotten about. I also do use a texture pack that changes the ice and fire items, however this is not the cause, since I also tried taking the texture pack off to see if the issue stayed, which it does. 
![weirdarmor](https://github.com/AlexModGuy/Ice_and_Fire/assets/98993704/f5d4c75b-738c-45ef-bd00-2b1cfd21ed2c)
I don't think I need to attach any log information, since I never experienced a crash while playing. So if there are plans to update this mod again for 1.18.2, this is something that I hope is fixed.

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
No crash was experienced, so no log, unless the logs have something to do with the armor clipping through the skin.
```

### Other Information

- [x] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SammieJay** [comment] 2023-12-30 22:06
This rly sucks, I wanted to have this mod in my 1.18.2 modpack but might not be able to now because of the way Armor looks :(

**Comment by TheBv** [comment] 2024-01-03 12:29
Duplicate of #4936

**Closed as completed by TheBv** 2024-01-03 12:29 UTC
Labels: bug, 1.18
