### ISSUE TITLE
Dragon looking the wrong way

### ISSUE THREAD

**Issue by carmifele** [Alex-the-666/Ice_and_Fire#4266] opened 2021-11-06 11:43 UTC
**Describe the bug**
if i'm riding a dragon and stand still, it tries to look either left, right, or fully backwards. walking solves it only for it to happen again once you stop

**To Reproduce**
1. Acquire a tamed dragon on growth stage 3
2. Ride it
3. Stay still
4. Look downwards

**Expected behavior**
The dragon looking foward and not trying to snap it's own neck

**Screenshots**

https://user-images.githubusercontent.com/93823346/140608271-15226811-ec81-409c-b8fa-0e428ba2f1ba.mp4

**Additional context**
Lighting dragons seem to suffer the most, while fire dragons suffer the least, though this doesn't mean they work as intended.

**Comment by TheBv** [comment] 2022-05-11 01:17
Duplicate of #4216

**Closed as completed by TheBv** 2022-05-11 01:17 UTC
